package com.netbiis.lojavirtual.model;
// Generated 25 de nov. de 2022 08:09:00 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name = "curso")
public class Curso implements java.io.Serializable {

	private Integer cursoId;
	private String titulo;
	private String descricao;
	private BigDecimal valor;
	private Set<Pagamento> pagamentos = new HashSet<Pagamento>(0);

	public Curso() {
	}

	public Curso(String titulo, String descricao, BigDecimal valor) {
		this.titulo = titulo;
		this.descricao = descricao;
		this.valor = valor;
	}

	public Curso(String titulo, String descricao, BigDecimal valor, Set<Pagamento> pagamentos) {
		this.titulo = titulo;
		this.descricao = descricao;
		this.valor = valor;
		this.pagamentos = pagamentos;
	}
	
	
	

	public String toString() {
		return "titulo: %s\ndescrição:%s\nid: %d, valor: %.2f".formatted(this.titulo,this.descricao, this.cursoId, this.valor.doubleValue());
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cursoId", unique = true, nullable = false)
	public Integer getCursoId() {
		return this.cursoId;
	}

	public void setCursoId(Integer cursoId) {
		this.cursoId = cursoId;
	}

	@Column(name = "titulo", nullable = false, length = 45)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "descricao", nullable = false, length = 500)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "valor", nullable = false, precision = 10)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "curso")
	public Set<Pagamento> getPagamentos() {
		return this.pagamentos;
	}

	public void setPagamentos(Set<Pagamento> pagamentos) {
		this.pagamentos = pagamentos;
	}

}
