package com.netbiis.lojavirtual.model;
// Generated 25 de nov. de 2022 08:09:00 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PagamentoId generated by hbm2java
 */
@Embeddable
public class PagamentoId implements java.io.Serializable {

	private int cursoId;
	private String cpf;

	public PagamentoId() {
	}

	public PagamentoId(int cursoId, String cpf) {
		this.cursoId = cursoId;
		this.cpf = cpf;
	}

	@Column(name = "cursoId", nullable = false)
	public int getCursoId() {
		return this.cursoId;
	}

	public void setCursoId(int cursoId) {
		this.cursoId = cursoId;
	}

	@Column(name = "cpf", nullable = false, length = 14)
	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PagamentoId))
			return false;
		PagamentoId castOther = (PagamentoId) other;

		return (this.getCursoId() == castOther.getCursoId()) && ((this.getCpf() == castOther.getCpf())
				|| (this.getCpf() != null && castOther.getCpf() != null && this.getCpf().equals(castOther.getCpf())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCursoId();
		result = 37 * result + (getCpf() == null ? 0 : this.getCpf().hashCode());
		return result;
	}

}
